In [27]:
import torch
import random

buffer_size = 10
batch_size = 5
buffer = torch.arange(0, buffer_size)*10

idx = random.sample(range(buffer_size), batch_size)
print(torch.randint(0, buffer_size, (batch_size,)))
print(torch.randperm(buffer_size))
print(idx)
print(buffer[idx])

tensor([2, 4, 9, 5, 8])
tensor([5, 3, 9, 7, 1, 6, 2, 4, 8, 0])
[6, 4, 1, 9, 7]
tensor([60, 40, 10, 90, 70])
